a = float(input("Введите первое число: "))
b = float(input("Введите второе число: "))

print(f"Cyммa: {a + b}")
print(f"Разность: {a - b}")
print(f"Произведение: {a * b}")
print(f"Деление: {a / b :.2f}")
print(f"Целочисленное деление: {a // b}")
print(f"Остаток: {a % b}")
print(f"Степень: {a ** b :.2f}")
